export const CATEGORY_ICONS: Record<string, string> = {
  "Food":             "food",
  "Coffee":           "cafe",
  "Candy":            "candy",
  "Fresh Fruit":      "fruits",
  "Beverages":        "beverages",
  "Flowers":          "flowers",
  "Desserts":         "desserts",
  "Other":            "other",
  "Personal Care":    "personal-care",
  "Wellness":         "wellness",
  "Fitness":          "fitness",
  "Event Services":   "event-services",
  "Custom Designs":   "custom-design",
  "Handmade":         "handmade",
  "Event":            "event",
  "Merchandise":      "merchandise",
  "General Services": "general-services",
  "Apparel":          "apparel",
  "Event Space":      "event-space",
  "Collectables":     "collectables",
  "Jewelry":          "jewelry",
  "Art":              "art",
};